CREATE TABLE `analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`culturalContext` varchar(64) NOT NULL,
	`riskScore` float NOT NULL,
	`journalText` text NOT NULL,
	`userImageUrl` text,
	`baselineImageUrl` text,
	`detectedEmotion` varchar(64),
	`emotionConfidence` float,
	`openness` float,
	`conscientiousness` float,
	`extraversion` float,
	`neuroticism` float,
	`riskTolerance` float,
	`jungianArchetype` varchar(128),
	`archetypeStrength` float,
	`enneagramType` varchar(32),
	`enneagramTitle` varchar(128),
	`shadowSelf` text,
	`shadowState` varchar(64),
	`indigenousTraitName` varchar(128),
	`indigenousTraitScore` float,
	`temporalCategory` varchar(64),
	`ethicalCompliance` boolean DEFAULT true,
	`reasoningPath` text,
	`analysis` text,
	`actionUnits` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `analyses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `recommendations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`analysisId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`creator` varchar(255),
	`type` varchar(64) NOT NULL,
	`reasoning` text,
	`enneagramAlignment` varchar(128),
	`url` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `recommendations_id` PRIMARY KEY(`id`)
);
